# Generated by Django 3.2 on 2022-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20220301_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True),
        ),
    ]
