# Generated by Django 3.2 on 2022-03-01 19:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='area_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
