# Generated by Django 3.2.12 on 2026-09-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_provider_phone_and_servicearea_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ('id',)},
        ),
    ]
